creation_rules:
  # base_server
  - path_regex: pillar/secrets/base_server\.yaml$
    age: age19vf4528tkqxv9tm3ceckazupe9jv7ng8lx28l4xef94pxrlc5fqql8hnwu,age1uc6agaf37nvts2mgla6v54mlucf0q7076jedw88qmpckdd8ztpdq27vryk
  
  # Pomerium-spezifisch
  - path_regex: pillar/secrets/pomerium\.yaml$
    age: age19vf4528tkqxv9tm3ceckazupe9jv7ng8lx28l4xef94pxrlc5fqql8hnwu,age1uc6agaf37nvts2mgla6v54mlucf0q7076jedw88qmpckdd8ztpdq27vryk

  # Headscale-spezifisch
  - path_regex: pillar/secrets/headscale\.yaml$
    age: age19vf4528tkqxv9tm3ceckazupe9jv7ng8lx28l4xef94pxrlc5fqql8hnwu,age1uc6agaf37nvts2mgla6v54mlucf0q7076jedw88qmpckdd8ztpdq27vryk